title: "日々鳥景アーカイブ"
description: "鳥と風景のデジタルアーカイブ"
# ローカルテスト時は空にするのが最も安全です
baseurl: ""
url: ""

theme: minima
plugins:
  - jekyll-feed

header_pages:
  - index.html
  - archive.html
  - tags.html
  - profile.html