title: "日々鳥景アーカイブ"
description: "鳥と風景のデジタルアーカイブ"

baseurl: "/my-blog-archive" 
url: "https://tmasumolikebirds96gm-lang.github.io"

theme: minima
plugins:
  - jekyll-feed

header_pages:
  - index.html
  - archive.html
  - tags.html
  - profile.html